version: "3.8"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: php:8.2-fpm
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.dev/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${APP_PORT}:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./.dev/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  database:
    image: mysql:5.7.36
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: hackaton
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - database_data:/var/lib/mysql/
      - ./.dev/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  php-my-admin:
    image: phpmyadmin/phpmyadmin
    container_name: php-my-admin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    networks:
      - app-network
    ports:
      - 8081:80

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  database_data:
